#!/bin/sh
#
# Sample CGI shell script to convert the named HTML file to PDF on-the-fly.
#
# Usage: http://www.domain.com/path/topdf/path/filename.html
#
# The filename on the command-line is relative to the document root of the
# server.  This script is slightly more secure than the topdf.cgi script
# since it will use the translated pathname coming from the HTTP server.
# Just make sure your HTTP server is secure...
#

docroot=`dirname $PATH_TRANSLATED`
cd $docroot

echo "Content-Type: application/pdf"
echo ""

htmldoc -t pdf --webpage $PATH_TRANSLATED
